### ISSUE TITLE
astro integration does not work with astro:i18n `prefixDefaultLocale: true`

### ISSUE THREAD

**Issue by stefanprobst** [Thinkmill/keystatic#1041]
in an astro project, which sets the [astro i18n option `prefixDefaultLocale`](https://docs.astro.build/en/guides/internationalization/#prefixdefaultlocale-true) to `true`, i cannot load `/keystatic` but instead see a 404 page.

not sure if there is something the keystatic astro integration needs to set, or if this is an upstream issue with `astro:i18n`.

issue repro: https://github.com/stefanprobst/issue-keystatic-astro-i18n-prefix

**Comment by emmatown** [comment]
This seems like expected behaviour, since `/keystatic` isn't prefixed with a locale, `prefixDefaultLocale` says it'll return a 404

**Comment by simonswiss** [comment]
Collating this in https://github.com/Thinkmill/keystatic/issues/1080
