### ISSUE TITLE
Mobile doesn't scale in admin using Astro

### ISSUE THREAD

**Issue by t1gu1** [Thinkmill/keystatic#1044]
Don't know if it's something for onthers, but in the Astro keyStatic Admin, it doesn't scale correctly.
Everything is way too small.

I just try to add that in the `head` and everything was fine:
`<meta name="viewport" content="width=device-width, initial-scale=1" />`

I try to fork the project to add it in a pull request, but I didn't find where the head was define.. :/

**Comment by t1gu1** [comment]
I made a PR: https://github.com/Thinkmill/keystatic/pull/1045
As i said, i don't find how to add something in the head tag..

At the end it give the same result.

**Comment by t1gu1** [comment]
Here a small example of the change that made. (Very more impactful in some other screens)

Before:
![image](https://github.com/Thinkmill/keystatic/assets/12479055/a689c613-37e7-4b8a-8520-7404252d7563)

After:
![image](https://github.com/Thinkmill/keystatic/assets/12479055/0c577f01-177c-4fa7-8060-2c0eb4f4ebe1)

**Comment by emmatown** [comment]
Fixed by #1045
