### ISSUE TITLE
Brand UI Mark Example don't works.

### ISSUE THREAD

**Issue by t1gu1** [Thinkmill/keystatic#1052]
In that doc page there is an example how to change the logo alias `mark` of the keystatic cms.

Here is the link: https://keystatic.com/docs/user-interface

But the example doesn't works.. 

P.S. I work with an a Astro project if it can change something.

Here the example: (I tried in few way with different image)

```javascript
// keystatic.config.ts
import { config } from '@keystatic/core'

export default config({
  ...
  ui: {
    brand: {
      name: 'Your brand',
      mark: ({ colorScheme }) => {
        let path = colorScheme === 'dark'
          ? '//your-brand.com/path/to/dark-logo.png'
          : '//your-brand.com/path/to/light-logo.png';
        
        return <img src={path} height={24} />
      },
    },
  },
})
```

---

Here is an example that works:

```javascript
// keystatic.config.ts
import { config } from '@keystatic/core'
import LogoDark from './public/logo-white.svg'
import LogoWhite from './public/logo-dark.svg'
import React from 'react';

export default config({
  ...
  ui: {
    brand: {
      name: 'Your brand',
      mark: ({ colorScheme }) => {
        let themeLogo = colorScheme === 'dark' ? LogoDark.src : LogoWhite.src
        
        return React.createElement("img", {src: themeLogo, width: 30})
      },
    },
  },
})
```

---

Maybe there is a bug to fix for the actual example to works?
Well there is my workaround if it is.

**Comment by t1gu1** [comment]
How that change fix things?
It didn't even change the example. O.o

Sorry, not sure to understand. @emmatown

**Comment by emmatown** [comment]
To use JSX, you need to rename `keystatic.config.ts` to `keystatic.config.tsx`, yes. `keystatic.config.ts` is fine if not using JSX which the other examples aren't
