### ISSUE TITLE
Deploy keystatic with astro to cloudflare

### ISSUE THREAD

**Issue by Lenne231** [Thinkmill/keystatic#1056]
Hello,

I'm trying to deploy my astro page with keystatic to cloudflare. I have set the `output` of astro to `hybrid` so that I can compile andd added the cloudflare integration.

But there seems to be a size limit for workers in cloudflare. The following error comes up during depoyment to cloudflare:

`Your Functions script is over the 1 MiB size limit (workers.api.error.script_too_large)`

The `_worker.js` folder of the output is currently 6.6 MiB. Is there a way to get around this?

**Comment by emmatown** [comment]
Subscribing to the paid Workers plan increases the limit so the worker can fit

**Comment by Lenne231** [comment]
Ahh ok, thanks!

What is the reason for the size of the worker? My assumption was that keystatic is using the GitHub API, which can also be called from the browser. Would it be possible to run it completely in the browser? I think for authenticating to the GitHub API, a server is needed, or are there more features that need a server?
