### ISSUE TITLE
RangeError An error occurred. Invalid time value

### ISSUE THREAD

**Issue by neo-art** [Thinkmill/keystatic#1098]
Hello,

I am trying to add Keystatic to the existing Astro project but I got the following error message:
RangeError
An error occurred.
Invalid time value
date-fns/format.mjs:352:11
<img width="1296" alt="Screenshot 2024-04-25 at 22 27 11" src="https://github.com/Thinkmill/keystatic/assets/5845802/61ec9c45-12d4-4b70-b986-693f58970740">

Any idea what can cause the issue?

This is the template I am adding Keystatic:
[https://github.com/themefisher/bookworm-light-astro.git](https://github.com/themefisher/bookworm-light-astro.git)

**Comment by emmatown** [comment]
date-fns isn't used by Keystatic so this isn't an issue with Keystatic. date-fns looks to be used by the template you're using, that means somehow an invalid date being passed in there

**Comment by neo-art** [comment]
Understood, appreciate the response
