### ISSUE TITLE
Expose markdoc/nodes configuration within keystatic config

### ISSUE THREAD

**Issue by jmduke** [Thinkmill/keystatic#1108]
We're porting our docs to Markdoc (backed by Keystatic) and got bitten pretty hard by the issue described in https://github.com/markdoc/markdoc/issues/72 and https://github.com/markdoc/markdoc/issues/306 because our docs have a lot of handlebar-ish code blocks, and it's somewhat hard to enforce the process=false tag in every single code block. Per https://github.com/markdoc/markdoc/discussions/504, it looks like we can override this by accessing the top-level `nodes` configuration within config, but afaict Keystatic doesn't expose that. Is there a way we could get access to that (potentially via `fields.document`?

**Comment by emmatown** [comment]
Keystatic itself never calls `Markdoc.validate` or `Markdoc.transform` and it doesn't have an internal Markdoc config (it just uses Markdoc's parser and formatter) so using that syntax inside code blocks should just work.
