### ISSUE TITLE
Automatically switch to 'local' mode when running on localhost

### ISSUE THREAD

**Issue by alexander-entin** [Thinkmill/keystatic#1145]
so that there is not need to switch the mode in the config for development/deployment

**Comment by emmatown** [comment]
There are various reasons to use non-local mode in development so this isn't something we're interesting in doing automatically. You can easily do it yourself though e.g.

```js
storage: process.env.NODE_ENV === 'production' ? { kind: 'github', repo: 'owner/name' } : { kind: 'local' }
```
