### ISSUE TITLE
all overlays broken since 0.5.20

### ISSUE THREAD

**Issue by stefanprobst** [Thinkmill/keystatic#1181]
repro: https://github.com/stefanprobst/issue-keystatic-overlays

in current keystatic versions, all overlays (dialogs etc.) are not shown. i only see the dimmed background, but nothing else.

last known version to work is 0.5.19 for me.

to reproduce, clone the [repro](https://github.com/stefanprobst/issue-keystatic-overlays) and in the keystatic ui, add a "Post" and click the "Add" Cards button => see the background being dimmed but nothing else being shown.

when pinning keystatic to 0.5.19 everything works:
```json
"pnpm": {
  "overrides": {
    "@keystatic/core": "0.5.19"
  }
},
```

**Comment by arihantverma** [comment]
I can confirm. I am facing this as well.
