### ISSUE TITLE
'/node_modules/lodash/debounce.js?v=1a485ea4' does not provide an export named 'default'

### ISSUE THREAD

**Issue by Matthijz98** [Thinkmill/keystatic#1193]
I am trying to migrate to the new content components but as soon as i add a wrapper, block or inline Keystatic stops working
![image](https://github.com/Thinkmill/keystatic/assets/17087153/cf3cf6e4-19c2-422a-a0f3-205e182236dc)
That points to this import ``import debounce from "/node_modules/lodash/debounce.js?v=1a485ea4";``
I am on the newest version of Astro, Keystatic and the Keystatic Astro intergration.

This is the config:
```
const blocks = {
    Lichtkarakter: block({
        label: 'Lichtkarakter',
        schema: {
            karakter: fields.text({label: 'Karakter'}),
        },
    }),
}
....
content: fields.markdoc({
    label: 'Content',
    extension: 'mdoc',
    options: {
        image: {
            directory: `src/assets/${col.path}/images/`,
            publicPath: `@assets/${col.path}/images/`,
            schema: {
                title: fields.text({
                    label: 'Caption',
                    description:
                        'The text to display under the image',
                }),
            },
        },
    },
    components: blocks,
}),
....
```

**Comment by emmatown** [comment]
I can't reproduce this, could you provide a GitHub repository that reproduces the issue?

**Comment by Greenheart** [comment]
I could reproduce this by switching the import-order of `keystatic()` and `react()` in my `astro.config.js`.

The fix was to make sure React was registered before Keystatic.
