### ISSUE TITLE
Main Website -> Can't Login

### ISSUE THREAD

**Issue by TheGreatAxios** [Thinkmill/keystatic#1200]
Hi -- just wanted to let you know when trying to login to your "cloud"; I can't. 
It just says resend verification email and never comes through.

**Comment by emmatown** [comment]
Email delivery seems to working fine, the only recent failures were for domains where MX records couldn't be resolved, this might be you if you mistyped your email or etc. I've just updated the email verification page to show the email that was signed up with so you can see if that's the case. If those failures were you, you should create a new account with the correct email.
