### ISSUE TITLE
Filenames with umlauts break git workflow => Rename files before commit

### ISSUE THREAD

**Issue by tordans** [Thinkmill/keystatic#1224]
I had this issue way back when I used [cloudcannon](https://cloudcannon.com/) in another company:

When you upload a file like `Übesicht Kommunensteckbriefe Text.png` via the web UI, this file is stored unter this name in Github:
> <img width="699" alt="image" src="https://github.com/Thinkmill/keystatic/assets/111561/f674ae42-399a-4b80-b973-6ff537e41544">

However, when you pull your change to a Mac git is super confused and run into a loop:

It shows the files as "new", even though nothing changed:
> <img width="499" alt="image" src="https://github.com/Thinkmill/keystatic/assets/111561/e4877304-5c01-4b73-ac65-b75729b50d09">

When you then discard those changes that you never did…
> <img width="770" alt="image" src="https://github.com/Thinkmill/keystatic/assets/111561/8d0b850f-3e5c-47d8-a375-a73131836cc5">

… the files still show up as changes:
> <img width="493" alt="image" src="https://github.com/Thinkmill/keystatic/assets/111561/853aa64f-b0a6-4baf-a6fb-988a4e941f59">

You can discard those changes and get back to the version with the green `+` from above. Its a loop.

From what I remember, this has to do with different encoding settings in Git (maybe only on the mac).
Years ago I tried fiddeling with different git settings but that only caused different issues.

This is the article I bookmarked back then https://stackoverflow.com/questions/5581857/git-and-the-umlaut-problem-on-mac-os-x

I tried the `core.precomposeunicode` again today but that did not change anything.

---

Given this issue, it would be awesome to have an option that renamed files when they are uploaded to an URL save version. Like a sluggified filename.

Is something like this possible in Keystatic?

**Comment by tordans** [comment]
https://github.com/Thinkmill/keystatic/issues/1116 is related. I don't have the issue with spaces but it could also be solved by modifying the image file name during upload.

**Comment by roman-koshchei** [comment]
Yes, I have the exact same issue here. Just having option to create random unique filenames will solve it

**Comment by roman-koshchei** [comment]
Option like uniqueFilename which will generate random filename will be so amazing:

![image](https://github.com/user-attachments/assets/b9d88d75-dc2f-4ed5-a64b-59021ba1ba0b)
