### ISSUE TITLE
Keystatic is unable to find environment variables when deployed with Cloudflare

### ISSUE THREAD

**Issue by picafe** [Thinkmill/keystatic#1229]
I am currently using Astro with Cloudflare (adapter version 11.0.1) and it seems like Keystatic cannot access the environment variables set in the Cloudflare pages project dashboard. 
As seen, I have the env variables set in my project dashboard:
![image](https://github.com/user-attachments/assets/2126b8a3-c66e-45b3-ac0f-0dd271542032)
When I try to access the keystatic URL (/keystatic), I can see in the Cloudflare function logs that:
/api/keystatic/github/refresh-token
```
  "logs": [
    {
      "message": [
        "09:31:29 [ERROR] Error: Missing required config in Keystatic API setup when using the 'github' storage mode:\n- clientId (can be provided via KEYSTATIC_GITHUB_CLIENT_ID env var)\n- clientSecret (can be provided via KEYSTATIC_GITHUB_CLIENT_SECRET env var)\n- secret (can be provided via KEYSTATIC_SECRET env var)\n\nIf you've created your GitHub app locally, make sure to copy the environment variables from your local env file to your deployed environment\n    at makeGenericAPIRouteHandler (chunks/keystatic-api_Uop07FqP.mjs:763:13)\n    at makeHandler (chunks/keystatic-api_Uop07FqP.mjs:1221:19)\n    at chunks/keystatic-api_Uop07FqP.mjs:13769:13"
      ],
      "level": "error",
      "timestamp": 1721035889075
    }
  ],
  ```
  The page does load, but when I click log in with Github, it returns with a 500 server error:
  /api/keystatic/github/login
  ```
    "logs": [
    {
      "message": [
        "09:34:10 [ERROR] ReferenceError: Cannot access 'ALL' before initialization\n    at renderEndpoint (chunks/astro/server_CQqo3MdJ.mjs:105:37)\n    at lastNext (bundledWorker-0.7162887875116892.mjs:1421:29)\n    at next (bundledWorker-0.7162887875116892.mjs:870:33)\n    at bundledWorker-0.7162887875116892.mjs:846:18\n    at onRequest (_noop-middleware.mjs:2:32)\n    at applyHandle (bundledWorker-0.7162887875116892.mjs:825:22)\n    at bundledWorker-0.7162887875116892.mjs:844:18\n    at payload (bundledWorker-0.7162887875116892.mjs:57:25)\n    at applyHandle (bundledWorker-0.7162887875116892.mjs:825:22)\n    at bundledWorker-0.7162887875116892.mjs:822:12"
      ],
      "level": "error",
      "timestamp": 1721036050910
    }
  ],
  ```
I assume this is expected because of the previous error.
I have tried deploying with Netlify (using the latest version of the Netlify adapter) and when I set the environment variables in the dashboard, it works as expected (no errors). It also works locally when using a .env file. 

I am wondering if this is an error on my part, with Keystatic or the adapter. Any help would be very appreciated, thank you!

**Comment by webdevlogics** [comment]
I was having the same issue, that you were. It has something to do with how Astro handles ENV variables. 

Update your astro.config.mjs . Add the vite line.

![cloudflare-keystatic-env-issue](https://github.com/user-attachments/assets/1b0280b4-2691-47c8-9046-de5e8ae89e28)

**Comment by picafe** [comment]
> I was having the same issue, that you were. It has something to do with how CloudFlare and Astro handle ENV variables.
> 
> Update your astro.config.mjs . Add the vite line.
> 
> ![cloudflare-keystatic-env-issue](https://private-user-images.githubusercontent.com/134076731/350177606-1b0280b4-2691-47c8-9046-de5e8ae89e28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjk1MzYsIm5iZiI6MTcyMTM2OTIzNiwicGF0aCI6Ii8xMzQwNzY3MzEvMzUwMTc3NjA2LTFiMDI4MGI0LTI2OTEtNDdjOC05MDQ2LWRlNWU4YWU4OWUyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNjA3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTc1YjhhOGM2YzdkNzcyYWZkZGQyYzNlYzJjY2IxNWU3YjI3MzU2NjJmZWRiNTliYmJmMTUyYmFhZmExODM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Flc74OmbBEPk6aC2A3uifmQMNHTTz_ajML4wc5fqo64)

thanks for letting me know! this solved the issue for me

**Comment by radenpioneer** [comment]
It's no  longer working.
