### ISSUE TITLE
Custom blocks aren't shown when markdoc field isn't focused

### ISSUE THREAD

**Issue by jasikpark** [Thinkmill/keystatic#1236]
https://github.com/user-attachments/assets/8e010b79-f57c-4a0b-b9ab-67ebf1bb6c7a

For some reason, the custom blocks for a document don't render until I focus the input, they don't even render placeholders. I'd really appreciate if they always fully loaded in.

**Comment by emmatown** [comment]
I'm not able to reproduce this, could you share a GitHub repo that reproduces this and which browser & browser version you're using?

**Comment by zanhk** [comment]
Can confirm the problem exist

[google_screen_recording_2024-07-23T20-27_01.630Z.webm](https://github.com/user-attachments/assets/b8e1374b-24b9-4f12-8aee-20de76f0b031)
