### ISSUE TITLE
Fail in building due to 'Cannot bundle Node.js built-in "node:path"'

### ISSUE THREAD

**Issue by VictorMartinezKwua** [Thinkmill/keystatic#1259]
Builds are failing due to:
`[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "node:path" imported from "node_modules/.pnpm/@keystatic+core@0.5.32_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@keystatic/core/dist/keystatic-core-reader.worker.js". Consider disabling ssr.noExternal or remove the built-in dependency.`

Also I see that:
WARN  deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 
 I don't know if this can be a problem but this packages seems to be called by @keystatic/core
 
 This starts happen when I updated the @astro/cloudflare dependenci to 11.0.3 and astro to 4.13.1
 
My astro.config:
```
export default defineConfig({
  integrations: [react(), markdoc(), keystatic(), tailwind(), mdx()],
  output: 'hybrid',
  adapter: cloudflare(),
  vite: {
    ssr: {
      noExternal: ['@keystatic/core']
    },
  }
});
```

I tried to modify vite build behavior as you can see, recommendated by the log I show at start of the issue:
"Consider disabling ssr.noExternal or remove the built-in dependency."

**Comment by amirzezo201** [comment]
Iam also facing the same issue 

 external: ["buffer", "path", "fs", "os", "crypto", "async_hooks"].map(
        (i) => `node:${i}`
      ),
      
      i added this now the path error is gone but now i see node/fs promise error

**Comment by emmatown** [comment]
It looks like you're using the `@keystatic/core/reader` in a dynamically rendered page which won't work in environments like Cloudflare Workers since they don't have a file system, you should likely render whatever pages use the `@keystatic/core/reader` at build time.

**Comment by vivgui** [comment]
For future reference, I had this same issue and when I switched to using the [createGitHubReader](https://keystatic.com/docs/reader-api#git-hub-repository) method then I could deploy to CF Pages and use the Reader API without issues.
