### ISSUE TITLE
Invalid type resolve for `fields.ignored()`, filed exist in DOCS but not in types

### ISSUE THREAD

**Issue by devzom** [Thinkmill/keystatic#1267]
Tried to use `fields.ignored()` but seems like it's deprecated type or it's missing in the file definition.
cc https://keystatic.com/docs/fields/ignored

**Comment by emmatown** [comment]
The field definitely exists in the published types: https://docsmill.dev/npm/@keystatic/core@0.5.41#/.fields.ignored. You might have been on an older version of Keystatic
