### ISSUE TITLE
Keystatic Cloud: only 30 repositories can be chosen when creating a new project

### ISSUE THREAD

**Issue by juliendargelos** [Thinkmill/keystatic#1299]
When creating a new project on Keystatic Cloud, and despite choosing "All repositories" when authorizing the Keystatic GitHub app; only 30 repositories are shown in the picker field, mainly the oldest ones:

<p align="center">
<img width="537" height="560" src="https://github.com/user-attachments/assets/7bea9a7b-a749-4e27-b87f-f15103b13c8b" alt="Capture d’écran 2024-09-08 à 22 13 59"/>

</p>

Looking at the http request responsible for getting this data, only 30 repositories are indeed returned, and no subsequent requests appear to expand this list later:

> Request:
> ```yaml
> url: https://keystatic.cloud/teams/[TEAM_SLUG]?_rsc=oc6sl
> method: get
> ```

> Response:
> ```yaml
> content-type: text/x-component
> body: |
>   [...]
>
>   11:["$","$L16",null,{"defaultOpen":false,"buttonLabel":"Add project","children":
>   ["$","$L17",null,{"installations":[{"id":**********,"owner":"juliendargelos","repos":
>   [{"name":"**********","id":**********},{"name":"**********","id":**********},
>   {"name":"**********","id":**********},{"name":"**********","id":**********},
>
>   [26 more repositories]
>
>   {"name":"**********","id":**********},{"name":"**********","id":**********},
>   {"name":"**********","id":**********},{"name":"**********","id":**********}]}],
>   "initialInstallationId":"$undefined","action":"$F18"}]}]
>
>   [...]
> ```

**Comment by emmatown** [comment]
This is now fixed

**Comment by juliendargelos** [comment]
Great thanks !

**Comment by juliendargelos** [comment]
This may have caused another issue though: #1302
