### ISSUE TITLE
Footnotes in Posts

### ISSUE THREAD

**Issue by nmandal** [Thinkmill/keystatic#140]

**Comment by jasikpark** [comment]
I assume this is a request for allowing "footnotes" in rich content - which could honestly just be another rich content type, similar to an inline link

I really like the way that https://edwardtufte.github.io/tufte-css/ does footnotes in the render :)

**Comment by jossmac** [comment]
Apologies for the lack of documentation, we're working on a few things at once so the APIs are a bit volatile.

If I understand correctly, you'd like to include some "footnote" element within the body of a post? The document field supports custom `componentBlocks` for this sort of thing. Here's an example of how you might implement:

```jsx
import { collection, component, config, fields } from '@keystatic/core';

export default config({
  ...
  collections: {
    posts: collection({
      label: "Posts",
      ...
      schema: {
        ...
        content: fields.document({
          label: "Content",
          componentBlocks: {
            footnote: component({
              label: "Footnote",
              chromeless: true,
              preview: (props) => (
                <blockquote>{props.fields.child.element}</blockquote>
              ),
              schema: {
                child: fields.child({
                  kind: "block",
                  placeholder: "Content...",
                }),
              },
            }),
          },
        }),
      },
    }),
  },
});
```
