### ISSUE TITLE
Astro: 'Cannot read properties of undefined (reading 'digest')' 

### ISSUE THREAD

**Issue by phenomen** [Thinkmill/keystatic#182]
I'm was following [Astro guide](https://thinkmill.notion.site/Add-Keystatic-to-an-Astro-Project-312e59b9be1f43d480d3f77638da2910) but got this error when trying to open Homepage singleton:

![chrome_zNbUzMl8IJ](https://user-images.githubusercontent.com/138311/226947242-24efd066-aaf8-4a74-9681-1ef5cf09d8cc.png)

**Comment by jasikpark** [comment]
Did restarting the process fix things? I just went through the astro starter docs and met no similar difficulties

**Comment by simonswiss** [comment]
Hey @phenomen — sorry for not having followed up on that.

The Astro setup has changed quite a bit (for the better) — new Astro features like [hybrid rendering](https://docs.astro.build/en/guides/server-side-rendering/#enabling-ssr-in-your-project) and [content collections support for Markdoc, YAML and JSON](https://docs.astro.build/en/guides/content-collections/) makes Astro and Keystatic work much better together!

Let me know if you still need help getting setup — I don't mind doing a PR into your repo to get you going.

**Comment by phenomen** [comment]
It's resolved with new Astro and Keystatic setup👍
