### ISSUE TITLE
Feature: Support Preact

### ISSUE THREAD

**Issue by airtonix** [Thinkmill/keystatic#225]
Not sure what the variation here is yet, but it's significant enough that it matters for #224 

I think it revolves around `React.forwardRef`

Typescript wise, it'll mean something around using import_maps to shim `react` into `preact/compat` (not entirely sure yet)

**Comment by simonswiss** [comment]
Hey!

There are no plans to support Preact. It's built on React, and that won't change. 

Keystatic itself has a fairly large bundle size, so using Preact isn't really going to make any difference.

Of course, it's fine to build your frontend with Preact, but Keystatic itself will stay on React.
