### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by NoelOConnell** [Thinkmill/keystatic#229]
Looks like as part of the install it tries to create a `.env` file using the `touch` command.
This doesn't exist on Windows.

![image](https://user-images.githubusercontent.com/966495/230352784-e3137cbf-ecc7-4481-bc2d-e25947445c74.png)

**Comment by emmatown** [comment]
The example project that used `touch .env` has been replaced with `npm create @keystatic@latest` so this is no longer relevant
