### ISSUE TITLE
`fields.array()` has missing info

### ISSUE THREAD

**Issue by jasikpark** [Thinkmill/keystatic#230]
In the main view of the editor, the array view of an element is incomplete.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/10626596/230547613-fe86ee12-2c1e-451d-8500-dc5ddb276fec.png">

This screenshot shows an empty list of images and a list of "Programming Languages" relationships, with one `astro` entry in that array.

```
images: fields.array({
  ...fields.object({
    image: fields.image({ label: "Image", directory: "public" }),
    alt: fields.text({ label: "Alt text" }),
  }),
}),
programmingLanguages: fields.array({
  ...fields.relationship({
    label: "Programming Languages",
    collection: "programmingLanguages",
    description: "Link the languages this tool supports",
  }),
}),
```

Not sure if I and the `keystatic-astro-docs` starter are configuring things wrong, or not?

I'd love to make a PR to fix -- just point me in the right direction :grin:

**Comment by emmatown** [comment]
You can pass a second argument to `fields.array` to configure the label of the array field, the label of items in the array field and a few other things.

Also, the spreading into an object before passing a field to `fields.array` shouldn't be there.

If you want to make a PR to `keystatic-astro-docs` to update these, that would be great!
