### ISSUE TITLE
Put comments for which file you're in inside the `---` in astro files

### ISSUE THREAD

**Issue by jasikpark** [Thinkmill/keystatic#231]
It'd be great if https://thinkmill.notion.site/Add-Keystatic-to-an-Astro-Project-312e59b9be1f43d480d3f77638da2910 could be updated to include the comments w/in the frontmatter, so that the snippets are valid Astro:

```astro
---
// src/pages/keystatic/[...params].astro
import { Keystatic } from '../../../keystatic.page'
---

<Keystatic client:only />
```

instead of

```astro
// src/pages/keystatic/[...params].astro
---
import { Keystatic } from '../../../keystatic.page'
---

<Keystatic client:only />
```

**Comment by simonswiss** [comment]
Sorry I am only seeing this now 😅

I have updated the comments to be inside the frontmatter, as suggested.

Thanks!

**Comment by jasikpark** [comment]
thxxx!
