### ISSUE TITLE
App in prod is always redirecting to 127.0.0.1 even when the callback URL is already set

### ISSUE THREAD

**Issue by danestves** [Thinkmill/keystatic#298]
I have set up my application with the production callback URL but is always redirecting me to localhost

```
http://127.0.0.1:3000/api/keystatic/github/oauth/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```

My app is on https://danestves.fly.dev/

**Comment by BarnabyBishop** [comment]
Hey @danestves 

We are looking in how we can improve this flow, but for now you should be able to update this in the Keystatic Github app app you added to your Github repo. 

Head to:
- Your repo > Settings > Github Apps 
- Click `Configure` on the Keystatic app you added
- ⚙️ App settings

There should be a few callback urls. 

If there is one with your production domain ensure it doesn't have any double forward slashes in its path. 
E.g. Change this: `https://danestves.fly.dev//api/keystatic/github/oauth/callback`
To this: `https://danestves.fly.dev/api/keystatic/github/oauth/callback`

If there aren't any production domains in the callback url list, add `https://danestves.fly.dev/api/keystatic/github/oauth/callback`
