### ISSUE TITLE
Overflow on file upload

### ISSUE THREAD

**Issue by florian-lefebvre** [Thinkmill/keystatic#332]
Clicking on "Choose file" or having currently an image selected causes the page to overflow horizontally

![image](https://github.com/Thinkmill/keystatic/assets/69633530/7d0e0232-442e-46d4-b1cd-17500c9a083f)

Loos like it's caused by this div since removing it solves the issue
![image](https://github.com/Thinkmill/keystatic/assets/69633530/278fb057-ba59-4170-be37-3fe175ef3f66)

**Comment by jossmac** [comment]
@florian-lefebvre should be fixed by #371. I don't have a windows machine handy, please confirm once released.
