### ISSUE TITLE
Enhancement: color-scheme

### ISSUE THREAD

**Issue by florian-lefebvre** [Thinkmill/keystatic#333]
Making `color-schema` `dark` on dark mode would be awesome so that we don't get white flashy scrollbars on windows

**Comment by jossmac** [comment]
We inject a script to check the client and adjust attributes as soon as possible. I'm not sure there's much more we can do without introducing cookies or something. We may revisit later, but it isn't priority right now.

**Comment by florian-lefebvre** [comment]
afaik this is solved now 👍
