### ISSUE TITLE
404 page while logging into github (astro integration)

### ISSUE THREAD

**Issue by JedWatson** [Thinkmill/keystatic#365]
### Discussed in https://github.com/Thinkmill/keystatic/discussions/360

Creating an issue from this to track the issue, cc/ @simonswiss @emmatown 

<div type='discussions-op-text'>

<sup>Originally posted by **eyrewiut** June 24, 2023</sup>
I have set up my site with keystatic and everything works fine, however there seems to be a glitch when logging into the cms.

When I click the "log in with github" button, it shows an unstyled 404 page as shown below, but if I reload the page it logs in and works fine thereafter.. I am trying to use the new "hybrid" rendering mode, but have also tried it with the standard SSR mode as well with the same result.

Does anyone have any idea what is causing this? 

URL: `/api/keystatic/github/login`
![screenshot of the 404 page displayed during login flow](https://github.com/Thinkmill/keystatic/assets/35190402/5c4c478a-265f-4b30-b8b2-0bee933d7d2d)

</div>

**Comment by iamyuu** [comment]
Hi, any update? I'm trying to deploy keystatic into vercel, and when I want to access it, it shows the login page, when I click the button it shows an application error, and when I refresh the browser it redirects to `http://127.0.0.1:3000`

**Comment by nomorejalapenos** [comment]
Same issue

**Comment by nomorejalapenos** [comment]
Could you guys, while there is no solution yet, make the "Log in with GitHub" button a regular hyperlink?
