### ISSUE TITLE
TypeError: layoutInfo is undefined

### ISSUE THREAD

**Issue by stefanprobst** [Thinkmill/keystatic#390]
hi, i am seeing a "layoutInfo is undefined" error when clicking the "Paragraph" select in the richtext editor.

steps to reproduce:

- npm create @keystatic@latest
- cd new-keystatic-project
- npm install
- npm run dev
- go to http://127.0.0.1:3000/keystatic/collection/posts/item/first-post
- click on the "Paragraph" select on the left side of the richtext editor toolbar

it looks like the error is coming from the `@react-aria/virtualizer` package

**Comment by fdnklg** [comment]
I experienced the same issue with the blog template but only locally. The deployed version on vercel works just fine.

**Comment by jossmac** [comment]
Are you running your app in strict mode? This may have been resolved by #377, which includes an upstream fix.

Related to #397

**Comment by jossmac** [comment]
@stefanprobst @fdnklg this should be resolved by updating to the latest version of `@keystatic/core` which is `0.0.109` at the time of writing.

Please let us know if that's not the case and we'll reopen the issue.

**Comment by stefanprobst** [comment]
yep thanks :+1:, confirmed to be working with v0.0.109.
