### ISSUE TITLE
Using the select field throws an error

### ISSUE THREAD

**Issue by wh1zk1d** [Thinkmill/keystatic#397]
When I'm trying to choose an option from the select field in the Admin UI, I get this error message:

![image](https://github.com/Thinkmill/keystatic/assets/8103530/c6f0d8b6-df2f-41ef-9b54-4ea843fb61d9)

This is the part of the schema in my config:

```tsx
caffeineSource: fields.select({
    label: "Brühmaterial",
    options: [
      { label: "Espresso", value: "espresso" },
      { label: "Kaffeepulver", value: "coffee" },
      { label: "Tee", value: "tea" },
    ],
    defaultValue: "espresso",
})
```

**Comment by iyansr** [comment]
Have same issue when i click "Paragraph" dropdown

**Comment by jossmac** [comment]
Are you running your app in strict mode? This may have been resolved by #377, which includes an upstream fix.

**Comment by iamyuu** [comment]
I got the same issue and I am using Astro, so my app is not in strict mode (I guess)

**Comment by jossmac** [comment]
@iamyuu which version of `@keystatic/core` are you on?

**Comment by iamyuu** [comment]
Ah, after upgrading to `0.0.109` it's works fine for me

**Comment by jossmac** [comment]
Fantastic! Thanks for letting us know
