### ISSUE TITLE
Label and Description missing for NumberField

### ISSUE THREAD

**Issue by emilienbidet** [Thinkmill/keystatic#426]
Hello !

I found a bug with NumberField.

The label and the description should appear but nothing is displayed for NumberFields.

Here is my schema
```ts
export default config({
  storage: {
    kind: "local",
  },
  collections: {
    hotels: collection({
      schema: {
        slug: fields.slug({
          name: {
            label: "Name",
          },
        }),
        distance: fields.integer({
          label: "Distance",
          description: "Distance from the place in meters",
          validation: {
            min: 0,
            max: 10000,
          },
        }),
        ...
```

And the result:
<img width="630" alt="CleanShot 2023-07-06 at 19 35 34@2x" src="https://github.com/Thinkmill/keystatic/assets/44983373/cf70c5ea-e292-4d89-bbdd-cb4670d0bcd4">

**Comment by JedWatson** [comment]
I just pushed a fix for this, will be on npm with the next release in a day or two.

Thanks for reporting it!

**Comment by emilienbidet** [comment]
Thank you boss ❤️
