### ISSUE TITLE
where is it?

### ISSUE THREAD

**Issue by dholdaway** [Thinkmill/keystatic#432]
Click Install & Authorize.

Aaaaannnnd… Here comes Keystatic! ✨

At this point, you're all setup with a fully deployed project using Keystatic. You can start creating, editing and deleting content.

whats the url?

**Comment by dholdaway** [comment]
lol

**Comment by JedWatson** [comment]
Hey @dholdaway sorry it's confusing. Is there a specific page on the site or guide you were following? Trying to pick up your thread so I can see where you got lost (or was it just the CLI to create a new project?)

cc/ @simonswiss we might need to put some more "here's the big picture" type docs together?

To try and answer the question of "what's the URL" —

You need to add Keystatic as routes into your own Next.js or Astro site as per the integration guides [here](https://keystatic.com/docs/installation-next-js)

Keystatic is then just a route in your app, so you can run it locally and it will get deployed wherever you host your website (e.g Vercel)

If your website is at `localhost:3000` or `mysite.com` then Keystatic will be at `localhost:3000/keystatic` or `mysite.com/keystatic` (right now the route has to be `keystatic`)

Once you've installed & authorised the GitHub app, you'll need to make sure you have the keys in your ENV, in most setups this will be sorted automatically but if you're having trouble share a bit more detail about which process you've followed and what your setup is and we'll help you get it sorted (and update the guides with anything that's missing)

**Comment by dholdaway** [comment]
so i followed the docs, i used one of your templates and deployed it to Vercel. 

i started with this 

https://keystatic.com/docs/quick-start

i cloned this 

https://github.com/Thinkmill/keystatic-starter-landing-page

i created the app and followed the instructions

so i went to /keystatic

i got the xxxx/keystatic-landing-page by [xxxx](https://github.com/xxxx) would like permission to screen

i click the authorise button, now i just land at a 

404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: lhr1::6njtr-1688891112704-4d8a3641db5a
