### ISSUE TITLE
KEY-210: Document how to use images inside the document field.

### ISSUE THREAD

**Issue by iRajatDas** [Thinkmill/keystatic#433]
Using images inside blogs is common, I found that the document editor that not provides an option to upload images. It would be nice feature if added.

Thanks

**Comment by JedWatson** [comment]
You can do this!

Just realised it's missing from the example in the docs, will fix that.

You can see the full type docs here for the features: https://docsmill.dev/npm/@keystatic/core@0.0.109#/.fields.document.DocumentFeaturesConfig

Here's a more complete example of how to configure all the features of the document field:

```js
content: fields.document({
  label: 'Content',
  links: true,
  layouts: [[1], [1, 1]],
  images: {
    directory: 'src/content/blog/_images',
    publicPath: '/src/content/blog/_images/',
    schema: {
      title: fields.text({
        label: 'Caption',
        description:
          'The text to display under the image in a caption.',
      }),
    },
  },
  dividers: true,
  formatting: {
    headingLevels: true,
    blockTypes: true,
    listTypes: true,
    inlineMarks: {
      code: true,
      bold: true,
      italic: true,
      underline: true,
      strikethrough: true,
    },
  },
  tables: true,
}),
```

**Comment by simonswiss** [comment]
I have [added this example to the docs](https://keystatic.com/docs/fields/document#other-configuration-options), so I'm going to close this issue 👍
