### ISSUE TITLE
New field: datetime

### ISSUE THREAD

**Issue by florian-lefebvre** [Thinkmill/keystatic#444]
Currently, the date field only supports the following format: "yyyy-mm-dd". Would be great to have a Datetime field to support iso strings like `2021-03-03T19:44:47`

**Comment by jossmac** [comment]
BTW @JedWatson We're most of the way there with the `DateField` https://keystar-ui.vercel.app/package/date-time/date-field. I just need to set aside some time to implement its companion `DatePicker` component that also includes a calendar dialog.

**Comment by emilienbidet** [comment]
Hello @florian-lefebvre and @JedWatson ! I need this feature too. I would like to contribute to this project to make this available asap.

If I understood well the fields ui are generated using the keystar-ui package is it right ?

Could someone guide me on where can I found where to start in this codebase ?

Thanks 
Emilien

**Comment by florian-lefebvre** [comment]
I think those are all the fields https://github.com/Thinkmill/keystatic/tree/main/packages/keystatic/src/form/fields

**Comment by emmatown** [comment]
Added in #552
