### ISSUE TITLE
createReader adds ~500kB to bundle size with /app directory

### ISSUE THREAD

**Issue by georgwindhaber** [Thinkmill/keystatic#453]
Steps to reproduce:
1. Create a new project with `npm create @keystatic@latest`
2. Build it (using yarn and nextjs)

Now `/` and `/[slug]` have a bundle size of over ~580kB.

It seems like `createReader` gets bundled into the client bundle, because when removing it it has the expected size of about ~70kB

Versions:
"@keystatic/core": "^0.0.109",
"@keystatic/next": "^0.0.11",
"next": "^13.4.4",

macOS 13.4 (22F66)
node v18.15.0

**Comment by JedWatson** [comment]
Thanks for the report @georgwindhaber

Can you share any more details on how to reproduce? Is the repo you're working on open source, or can you post a (possibly stripped back) example of how you're calling the reader here?

I took a look at an open source / real life example (the [SydJS website](https://sydjs.com)) and can't see a similarly large bundle being created, code here for reference - https://github.com/Thinkmill/sydjs-keystatic

So I'm wondering if it's something specific to your project or how you're using the Reader that's causing the large size, any other information you can provide might help us figure it out.

**Comment by georgwindhaber** [comment]
Hey, thanks for the fast reply!

I'm working on this project https://github.com/georgwindhaber/diesindnichtnormal but the steps to reproduce for me were very little:

```
npm create @keystatic@latest
-> Select next.js
-> ./bundle
cd bundle
yarn install
yarn build
```

And I'll end up with a build like this, where `/` and `/[slug]` are pretty large
<img width="639" alt="Screenshot 2023-07-16 at 08 14 27" src="https://github.com/Thinkmill/keystatic/assets/13214112/b588ae32-ebb7-4278-96f2-ddc5c278d4d4">

I hope this helps, thank you!

**Comment by JedWatson** [comment]
Yep, that's helpful, we'll take a look!

**Comment by JedWatson** [comment]
Got some more information about this — it seems like the way that fields are implemented in the codebase sometimes causes bundler heuristics to (incorrectly) include Keystatic Admin UI code (and the corresponding design system components) in front-end bundles.

We're going to keep looking into it further and ship a fix, which may include (for now) disabling custom fields. I'm not sure how much that feature is used anyway, so I'll open a separate issue to discuss and track it.

**Comment by georgwindhaber** [comment]
Thank you for the investigation!

For myself I can say that I don't use custom fields, but I just started with Keystatic (loving it so far!) and did not find it in the docs - but yeah, that's just my anecdotal  evidence

Thanks! :)
