### ISSUE TITLE
Unexpected token 'B', "Bad Request" is not valid JSON

### ISSUE THREAD

**Issue by samithaf** [Thinkmill/keystatic#475]
First of all Keystatic is a pretty cool idea!! So I just want to tryout Keystatic but sadly got the following error :(

**Steps to reproduce**

1. Follow the [official installation](https://keystatic.com/docs/installation-next-js) guide
2. Configure up to https://keystatic.com/docs/installation-next-js#keystatic-api-routes step
3. Visit http://domain/keystatic/singleton/homepage
4. Getting Unexpected token 'B', "Bad Request" is not valid JSON error.

**System Information**
```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0
    Binaries:
      Node: 18.3.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```
![Screenshot 2023-07-20 at 9 18 20 pm](https://github.com/Thinkmill/keystatic/assets/1860417/a419d61a-2c22-4263-96bf-9bf15dc4da75)

**Comment by JedWatson** [comment]
Hey @samithaf thanks for the report, we're going to try and reproduce it and see if we can figure out what's going on.

Are there any more details you can share that might help? (e.g have you connected a GitHub app, or is it running in local mode, etc)

If you can add me to the codebase, I'd be happy to take a look, haven't seen that error before.

**Comment by sresidovic** [comment]
Hey @samithaf 👋 

Do you get the same error after completing the https://keystatic.com/docs/installation-next-js#keystatic-api-routes step? We can reproduce the issue is we stop just before that step. We'll update the docs to make this clearer, but Admin UI needs API routes (without it Dashboard is the only page that works).

**Comment by samithaf** [comment]
@JedWatson Here [is a repo](https://github.com/samithaf/keystatic-app) which you can reproduce the error.

**Comment by JedWatson** [comment]
@samithaf thanks for that, I cloned the repo and can't see any issue, did you get it working based on @sresidovic's comment above?

**Comment by samithaf** [comment]
@JedWatson I can run https://github.com/Thinkmill/keystatic-starter-blog in my machine without above issue. So it's fine I can play with that :)

But the funny thing is my sample repo is working fine on another Windows machine ( usually Win gives all the problems )

**Comment by samithaf** [comment]
Looks like related to `Node.js 18.3.0` and I upgraded to `Node.js 18.18.2` it just worked.
