### ISSUE TITLE
Feature Request: White labelling / Customisation options

### ISSUE THREAD

**Issue by junwen-k** [Thinkmill/keystatic#489]
Greetings,

Thank you for this amazing open source CMS.

Currently, there seems to be no option for CMS dashboard white-labelling / customisation options.
The easiest way is to maybe allow customising the word "Keystatic" to something else which is located on the top left corner of the dashboard.

![image](https://github.com/Thinkmill/keystatic/assets/40173716/9c012327-e68f-4d18-808d-40fe99c2f604)

**Comment by jossmac** [comment]
@emmatown I think we could add "projectName" or something to `LocalConfig.storage`? If it's non-trivial let's move this to discussions.

**Comment by jossmac** [comment]
It just occurred to me that this would always be running on your machine, the developer is the only audience so branding doesn't really make sense.

We have some thoughts on white-labelling/customising in the future.
