### ISSUE TITLE
Trim space at the end of url

### ISSUE THREAD

**Issue by solrik** [Thinkmill/keystatic#495]
Content team can make a mistake of having space at the end of the url slug and it breaks the page. (404 throws up)

PS: @matojdowski faced this issue while working.

**Comment by JPrisk** [comment]
![image](https://github.com/Thinkmill/keystatic/assets/22569730/37e3e570-c85c-4950-8d17-08979fb34ac5)

see filename above

Issue is when a new collection item is being created, if the slug field includes whitespace at the end of the string it will name the file with this whitespace

Desired logic: remove whitespace from end of slug by default

**Comment by JedWatson** [comment]
Got it, we'll ship a fix for this soon
