### ISSUE TITLE
Cannot detect url path in image, uploaded using documents field

### ISSUE THREAD

**Issue by VeoScript** [Thinkmill/keystatic#499]
I uploaded this image using fields.document

![image](https://github.com/Thinkmill/keystatic/assets/26340308/0d228335-41eb-4493-9ecc-48e62aa619f7)

and  I am getting this image url, but there is no image detected in the UI

![image](https://github.com/Thinkmill/keystatic/assets/26340308/9a2a0913-9c40-47cb-b4ca-2bc7cfa106b1)

![image](https://github.com/Thinkmill/keystatic/assets/26340308/e903f159-1141-4002-b304-48ea9e7d48db)

**Comment by jossmac** [comment]
Make sure that the field is configured to [store and serve the image](https://keystatic.com/docs/fields/image#storage-options) where your framework expects.

**Comment by simonswiss** [comment]
Any luck with this @VeoScript?

As Joss mentioned, you'll need to configure the `directory` and `publicPath` options inside that `document` field to put the image where you want, and "construct" the image path reference in your templates:

![CleanShot 2023-08-09 at 13 25 20@2x](https://github.com/Thinkmill/keystatic/assets/485747/0818a5f8-65a7-40fb-9d07-093a30d7b251)

Example:

```diff
content: fields.document({
  label: 'Content',
  formatting: true,
+  images: {
+    directory: 'public/images/blog',
+    publicPath: '/images/blog'
+  }
})
```

Hope it helps!

**Comment by VeoScript** [comment]
Yes it works.
Thanks @simonswiss
