### ISSUE TITLE
File '.../keystatic.page.ts' is not a module (Astro project)

### ISSUE THREAD

**Issue by teinett** [Thinkmill/keystatic#506]
I am learning Keystatic with Astro project, using official docs from https://keystatic.com/docs/installation-astro.

I have typescript error in this file /src/pages/keystatic/[...params].astro:

```astro
---
import { Keystatic } from '../../../keystatic.page'

export const prerender = false
---
```

TS error: `File '.../learn-astro-keystatic/keystatic.page.ts' is not a module.ts(2306)` for the line `import { Keystatic } from "../../../keystatic.page";`

My tsconfig.json file:

```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Screenshot:**

![keystatic-astro-ts-error](https://github.com/Thinkmill/keystatic/assets/1038168/356f9468-ccf6-4480-b78c-5f03f00c636e)

**Environment:**

- Node: 18.17.0
- npm: 9.6.7
- MacOS: Catalina 10.15.7

```json
"dependencies": {
    "@astrojs/react": "^2.2.1",
    "@keystatic/astro": "^0.0.8",
    "@keystatic/core": "^0.0.114",
    "@types/react": "^18.2.18",
    "@types/react-dom": "^18.2.7",
    "astro": "^2.10.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

**Comment by simonswiss** [comment]
Did you create that `keystatic.page.ts` file you're trying to import, as per the guide?

> The Keystatic Admin UI is built with React. So that we can import and mount this app here with React, let's create a new file outside of the pages directory.

> I'll put it in the project root, alongside our Keystatic config file.

```ts
// keystatic.page.ts
import { makePage } from '@keystatic/astro/ui'
import keystaticConfig from './keystatic.config'

export const Keystatic = makePage(keystaticConfig)
```

**Comment by teinett** [comment]
Yes, I have file `keystatic.page.ts` in the root of the project. You can see it on the screenshot attached:

![keystatic-astro-ts-error-2](https://github.com/Thinkmill/keystatic/assets/1038168/a98b56dd-6691-4c88-b6dd-2593e8e3934a)

I have code of the project here: https://github.com/teinett/learn-astro-keystatic

**Comment by simonswiss** [comment]
I pulled your repo, ran `npm install` and `npm run dev`, and everything works fine.

<img width="737" alt="CleanShot 2023-08-14 at 16 19 39@2x" src="https://github.com/Thinkmill/keystatic/assets/485747/3aa0fadb-21b8-4e60-bf2d-1c0c1337ef36">

Is this still an issue for you? Perhaps try reload the TypeScript project in vscode?

<img width="265" alt="CleanShot 2023-08-14 at 16 19 24@2x" src="https://github.com/Thinkmill/keystatic/assets/485747/9561881b-b1b3-4510-8981-9c9d68218985">

Let me know if this is still an issue.

I am no TS expert (as my reply shows 😅) but hopefully we can get you past this error!

**Comment by teinett** [comment]
Now I don't have this issue. Maybe, it was fixed after reloading of VSCode. OR, after the update of VSCode.
