### ISSUE TITLE
[AstroJS] crypto.subtle is undefined

### ISSUE THREAD

**Issue by teinett** [Thinkmill/keystatic#508]
I started new project Astro + Keystatic, using official docs https://keystatic.com/docs/installation-astro.

I setup my first collection "posts" and tried to create first post.

<img width="1001" alt="keystatic-astro-first-post" src="https://github.com/Thinkmill/keystatic/assets/1038168/c71055b9-6b02-4e00-b8f0-667ea61559ed">

**I got error**: 
```
crypto.subtle is undefined
```

Node: 18.17.0
npm: 9.6.7
MacOS: Catalina 10.15.7

"dependencies": {
"@astrojs/react": "^2.2.1",
"@keystatic/astro": "^0.0.8",
"@keystatic/core": "^0.0.114",
"@types/react": "^18.2.18",
"@types/react-dom": "^18.2.7",
"astro": "^2.10.3",
"react": "^18.2.0",
"react-dom": "^18.2.0"
}

**Comment by simonswiss** [comment]
Hey!

Are you able to share a repo where this issue happens? I am not able to reproduce this.

**Comment by teinett** [comment]
@simonswiss I have code of the project here: https://github.com/teinett/learn-astro-keystatic

**Comment by teinett** [comment]
I repeated the process in another test project with the same result. 

First I had this error: 

![2023-08-09 23-38-44](https://github.com/Thinkmill/keystatic/assets/1038168/fd5aab5b-5c28-4d9a-8443-f0178172592a)


I continued the integration Keystatic + Astro guide and received another error: 

![2023-08-09 23-39-41](https://github.com/Thinkmill/keystatic/assets/1038168/1861d68e-bed4-4685-8689-43fee09dfda1)

**Comment by simonswiss** [comment]
Hey 👋

`crypto.subtle`, which we actually use, is only available in "secure contexts" (~roughly `https` or `localhost` or `127.0.0.1`) — see https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle 

From your screenshot, you're not in a "secure context".

<img width="421" alt="CleanShot 2023-08-10 at 15 59 33@2x" src="https://github.com/Thinkmill/keystatic/assets/485747/626ea46e-1b6f-4da7-9f8d-31be46152948">

That's probably why you hit the error!

**Comment by teinett** [comment]
OK, I understood. 

Is it possible to do anything with it for local development?

**Comment by emmatown** [comment]
Accessing it via `127.0.0.1` should work

**Comment by teinett** [comment]
> Accessing it via `127.0.0.1` should work

I can't use 127.0.0.1:3000/keystatic, because of this error: https://github.com/Thinkmill/keystatic/issues/366. So use command `npm run dev`, which gives me this IP address.

```
➜  keystatic-astro npm run dev

> astro-keystatic@0.0.1 dev
> astro dev --host

  🚀  astro  v2.10.3 started in 502ms

  ┃ Local    http://localhost:3000/
  ┃ Network  http://192.168.1.67:3000/

12:22:40 AM [content] Watching src/content/ for changes
12:22:41 AM [content] Types generated
12:22:42 AM [astro] update /.astro/types.d.ts
```

My package.json:

```
{
  "name": "astro-keystatic",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev --host",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    ...
  }
}

```

**Comment by Maarten-Dekker** [comment]
Put this in your package.json and it should work:
"scripts": {
        "dev": "astro dev --host 127.0.0.1",
},

**Comment by teinett** [comment]
> Put this in your package.json and it should work: `"dev": "astro dev --host 127.0.0.1"`

I did it. The described error gone.

```
➜  keystatic-astro npm run dev

> astro-keystatic@0.0.1 dev
> astro dev --host 127.0.0.1

  🚀  astro  v2.10.3 started in 383ms

  ┃ Local    http://127.0.0.1:3000/

06:01:51 PM [content] Watching src/content/ for changes
06:01:52 PM [content] Types generated
06:01:52 PM [astro] update /.astro/types.d.ts
```

![2023-08-10 18-03-33](https://github.com/Thinkmill/keystatic/assets/1038168/eb54c3a2-ed2f-48f5-8544-c3488bd42247)
