### ISSUE TITLE
Better DX / documentation for the Document field

### ISSUE THREAD

**Issue by JedWatson** [Thinkmill/keystatic#531]
Our Document field is a bit obscure to get running successfully with, a few things we can do to improve it:

- [x] Only include valid markdown formatting options when you're using [shorthand syntax](https://keystatic.com/docs/fields/document#usage-example)
- [x] Document what the shorthand syntax expands into, and include an example of the **full** [reference of fields](https://docsmill.dev/npm/@keystatic/core@0.0.115#/.fields.document.FormattingConfig) that are available
- [ ] Explain that turning on other features will require custom tags in your MarkDoc rendering, ref #504
- [ ] Add dev example projects that show how to render the full set of formatting options, in Next.js (with Reader) and Astro (with Markdoc integration)

**Comment by emmatown** [comment]
Closing since the document field is now deprecated and we have better docs for the new editor fields
