### ISSUE TITLE
Astro http://127.0.0.1:3000/keystatic and unable to connect

### ISSUE THREAD

**Issue by tiwka19** [Thinkmill/keystatic#537]
I did everything according to the instructions in the documentation. When I go to the /keystatic path, I get a connection error

**Comment by Maarten-Dekker** [comment]
Any repo or screenshots to share? Try creating a new project:
`npm create @keystatic@latest`
Does /keystatic work for you in that project?

**Comment by tiwka19** [comment]
> Any repo or screenshots to share? Try creating a new project: `npm create @keystatic@latest` Does /keystatic work for you in that project?
