### ISSUE TITLE
Error: "lodash" does not provide an export member "get"

### ISSUE THREAD

**Issue by lstephensca** [Thinkmill/keystatic#580]
I was interest in learning more about Keystatic, so I gave it a go with the "astro-content" under dev-projects (mainly since it differed from the docs). I apologize if I shouldn't have been looking there, but I just want to point out the following error if you tried to use it:

Uncaught (in promise) SyntaxError: The requested module '/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js?v=aa3ff6fd' does not provide an export named 'get' (at keystar-ui-style.esm.js?v=aa3ff6fd:7:10)

**Comment by JedWatson** [comment]
Hey @lstephensca, thanks for opening the issue

What's going on here is a long story, but basically it's a problem with Vite bundling CommonJS components we're using in the Admin UI, that's specific to the way Astro includes the dependencies, with the integration.

The problem doesn't happen when you add the Astro routes for Keystone's Admin UI in your own project, which is the way the Keystatic CLI will generate a new Astro project.

The dev-projects aren't necessarily somewhere you shouldn't be looking 🙂 but they're not guaranteed to work, especially outside the monorepo, we're maintaining separate templates that are production ready, you can see the open source projects here: https://uses.keystatic.com/

(and also the CLI should always work for a blank project)

Hopefully we'll resolve the issues with Vite / Astro soon, and be able to ship the simpler integration mode 🤞
