### ISSUE TITLE
Bug: allow inline nodes

### ISSUE THREAD

**Issue by florian-lefebvre** [Thinkmill/keystatic#593]
When having this kind of content

```md
![](/some-image.png)This is the start of paragraph
```
I get this error
![image](https://github.com/Thinkmill/keystatic/assets/69633530/098e2048-9cd0-400e-982d-608a7aaab4e4)
Would be great to support this

**Comment by JedWatson** [comment]
Did you enable [images in the editor config](https://keystatic.com/docs/fields/document#other-configuration-options)?

This syntax certainly should work.

(also, I don't _think_ this should matter, but I'm not sure if the lack of whitespace between the image and the following text is intentional? Try putting a space between them, if it works then, there's a bug in the parser)

**Comment by JedWatson** [comment]
Oh. Actually I may not have read the question properly. If you already have images configured and they're working, but you can't use them inline with text, then I'm going to have to get back to you on that.

**Comment by florian-lefebvre** [comment]
I think so
![image](https://github.com/Thinkmill/keystatic/assets/69633530/7a28619c-67db-443e-9825-a3829dbcd4bd)

**Comment by florian-lefebvre** [comment]
@JedWatson I'm trying to get keystatic working again and still facing the issue in latest version of keystatic, can I help in any way?

**Comment by JackDevAU** [comment]
I'm also running into this issue when updating to the latest

From 

    "@keystatic/core": "^0.1.0",
    "@keystatic/next": "^1.0.0",
    "@markdoc/markdoc": "^0.3.2",
    
To: 
    
    "@keystatic/core": "^0.1.7",
    "@keystatic/next": "^1.0.1",
    "@markdoc/markdoc": "^0.3.4",

**Comment by florian-lefebvre** [comment]
To be precise, it happens with any inline nodes, turns out I have some inline paragraph nodes somehow

**Comment by florian-lefebvre** [comment]
Example of inline image:
```md
some text ![](image.png) some other text
```
For the inline paragraph, I don't even manage to spot where the issue, I'll reach out in Discord DM because I can't put the whole markdown here

**Comment by emmatown** [comment]
This is supported in the new markdoc and mdx fields, we don't have plans to add it to the document field and would encourage people to switch to the new fields
