### ISSUE TITLE
Importing @keystatic/core will increase the bundle size by 500kB+

### ISSUE THREAD

**Issue by syfxlin** [Thinkmill/keystatic#601]
## Description

After importing @keystatic/core into the Next.js application directory, any page that references keystatic will load the Keystatic UI bundle js and dependencies.

![bundle size image](https://github.com/Thinkmill/keystatic/assets/28844480/e2b53568-4243-4bb0-9cbe-1b62bf534fb0)

After a brief investigation, I found that there are a lot of `import 'module'` statements in the `keystatic-core.{esm/cjs}.js` file, and Next.js is not able to do tree shaking on them, which results in a larger bundle output by Next.js.

![keystatic-core js file image](https://github.com/Thinkmill/keystatic/assets/28844480/3b521d84-04b8-4f72-aabc-77313c8e9003)

## Reproduction steps

1. Clone this repository
2. Go to templates/nextjs folder
3. Run npm install
4. Run npm run build
5. View console output

## My Project

When I remove the Keystatic UI page from the app directory, the First Load JS of the page is still 580kB+, and if I remove `import { something } from "@keystatic/core"` from the page, the First Load JS of the page will be the normal size (142kB+).

Abnormal size:

![image](https://github.com/Thinkmill/keystatic/assets/28844480/d47d1815-b50b-404d-9805-7ab83c7dd241)

![image](https://github.com/Thinkmill/keystatic/assets/28844480/85d0f0e4-56c2-490b-8290-4a681616a53b)

Normal size:

![image](https://github.com/Thinkmill/keystatic/assets/28844480/25747959-d467-4fec-8c40-b8aa25474057)

![image](https://github.com/Thinkmill/keystatic/assets/28844480/2c8e78ff-f4ef-4adb-a295-e8d83749f668)

## Versions

Template project:

@keystatic/core@0.1.1
@keystatic/next@1.0.0
@types/react@18.2.21
next@13.4.19
react-dom@18.2.0
react@18.2.0
typescript@5.2.2

My project:

@keystatic/core 0.1.1
@keystatic/next 1.0.0
@types/react 18.2.21
next 13.4.19
react-dom 18.2.0
react 18.2.0
typescript 5.2.2

**Comment by JedWatson** [comment]
Hey @syfxlin 

Thanks for the report, I think we've found the underlying problem and we'll try and address it as soon as possible.

What's happening is some large amount of Keystatic is being incorrectly bundled by Next.js when the Reader is imported. The most comprehensive fix will involve a reasonably large refactor of how fields work so that the amount of code the Reader actually needs to include is minimal, but that's a lot of work, so we're also going to see if we can find a quicker patch that reduces the bundle size 🤞

**Comment by syfxlin** [comment]
Hi @JedWatson,

I think the fastest way to reduce the size of the bundle at the moment is to change the way fields are imported into the component to dynamic import (use React.lazy or @loadable/component). When the page doesn't use these components, it won't be loaded, thus reducing the First Load JS size for regular pages.

But this still loads the field's parse/serialize etc. methods, so I think it's best to improve the way fields work by splitting the Reader and UI into different bundles.

Thanks!
