### ISSUE TITLE
richtext field validation error for two adjacent list items

### ISSUE THREAD

**Issue by stefanprobst** [Thinkmill/keystatic#636]
for the following markdown content (two list items separated by empty line):

```md
- one

- two
```

the richtext field displays this validation error message:

![Screenshot_20230910_113249](https://github.com/Thinkmill/keystatic/assets/20753323/a4cd1f3d-f06d-4532-8024-da280acc1c92)

reproduction: https://github.com/stefanprobst/issue-keystatic-document-field

**Comment by emmatown** [comment]
This was a limitation of the document field, the document field has now been deprecated and superseded by the markdoc and mdx fields which both support content like this
