### ISSUE TITLE
Field URL Validation not working

### ISSUE THREAD

**Issue by ArnavK-09** [Thinkmill/keystatic#661]
# Config:
![image](https://github.com/Thinkmill/keystatic/assets/69188140/389d6abe-0975-4e28-b077-0619754117aa)

# Not Working:
![image](https://github.com/Thinkmill/keystatic/assets/69188140/56dd2832-a7cf-4168-89c2-d042c36c5af1)

**Comment by JedWatson** [comment]
Discussed (with request for more information) in #665
