### ISSUE TITLE
Improve error handling 

### ISSUE THREAD

**Issue by JackDevAU** [Thinkmill/keystatic#704]
Hi Keystatic Team, 

### Description 

While content/entries seem to be more stable - the errors are confusing. 

### Issue 

When I went to add an image - it shows in the editor but on save it produces the below error (see screenshots). 

1. There is no way to know what the actual error is. 
2. The only way to fix it is via the markdown file (not the editor) which is a bad user experience. 
3. Throw an error if the filename is not valid 

### Solutions 

1. Make error messages more precise
2. Be able to fix the error in editor 

### Screenshots 

![image](https://github.com/Thinkmill/keystatic/assets/57518417/7b8768f9-1110-4c37-9140-15fa50a94736)
**Figure: Invalid image filename or invalid image file type**

**Comment by simonswiss** [comment]
This is due to an issue with Markdoc — Emma has opened a PR that should resolve this file name issue 👍

https://github.com/markdoc/markdoc/pull/474/files

**Comment by emmatown** [comment]
Since that PR has been merged into Markdoc and is just awaiting a Markdoc release, I'm going to close this since there's nothing more we can do
