### ISSUE TITLE
exports condition for esm in package.json should use `import` not `module`

### ISSUE THREAD

**Issue by stefanprobst** [Thinkmill/keystatic#764]
afaiu the `package.json#exports` condition for esm should be `import` not `module`.

see https://nodejs.org/api/packages.html#conditional-exports

the keystatic packages seem to use `module`, see https://github.com/Thinkmill/keystatic/blob/main/packages/keystatic/package.json and https://github.com/Thinkmill/keystatic/blob/main/packages/next/package.json

(also, should the `types` field point to `.d.ts`?)

**Comment by emmatown** [comment]
Using the `module` condition rather than `import` is intentional because the ESM is aimed only at bundlers, not Node. The `types` field is also unnecessary since the `.d.ts` files are next to the `.js` files
