### ISSUE TITLE
Modify `date`/`datetime` field to render a `Date` instead of a string

### ISSUE THREAD

**Issue by rhyses-pieces** [Thinkmill/keystatic#821]
Hello! I've noticed that when I used the `date` or `datetime` field, it gets rendered with quotes.

For example: 
![image](https://github.com/Thinkmill/keystatic/assets/10332868/3d102275-bb59-4992-bf90-4ea472c18790)

Whereas, in the docs, it seemed like there were no quotes around the date field:
![image](https://github.com/Thinkmill/keystatic/assets/10332868/2dd87216-0890-4af1-ba34-8b6866709ab7)

Is this the intended behavior? If so, is there any way to modify it so that there are no quotes around the value in the date field?

**Comment by BikrantJung** [comment]
If the date is in string, you can create new Date() by passing in the date like:
```
const date = '2023-12-12'; // String
const newDate = new Date(date) // Date
```

**Comment by OliverSpeir** [comment]
I agree would be great if this was already a JS `Date` especially for astro content collections schema so we can use z.date()
