### ISSUE TITLE
Admin UI does not load if GitHub App installed to empty repo

### ISSUE THREAD

**Issue by tyteen4a03** [Thinkmill/keystatic#866]
# Description

Linking a Keystatic app to an brand new, uninitialized GItHub repo would cause the Admin UI to be completely blank.

# Reproduction

1. Create a Keystatic app and run it in development.
2. Link it to a brand new repository. (I used an organization one but I don't think it matters)
3. Try to access https://127.0.0.1/keystatic

**Comment by simonswiss** [comment]
I'm not sure I understand the use case where you'd want to do that. Keystatic in `github` mode will read/write content from the GitHub repository directly, so it's a fair assumption to expect that repo to have a Keystatic project committed.

Do you have a use case/workflow where that's an issue and the code for the repo cannot be committed and pushed?

**Comment by tyteen4a03** [comment]
> I'm not sure I understand the use case where you'd want to do that. Keystatic in `github` mode will read/write content from the GitHub repository directly, so it's a fair assumption to expect that repo to have a Keystatic project committed.
> 
> Do you have a use case/workflow where that's an issue and the code for the repo cannot be committed and pushed?

When you create a Keystatic project.

**Comment by tyteen4a03** [comment]
Yes, I think this experience should be improved so an error message shows you exactly what you need to do.
