### ISSUE TITLE
`@keystatic/astro@3.0.0`: /keystatic route does not work

### ISSUE THREAD

**Issue by phenomen** [Thinkmill/keystatic#894]
1. `pnpm create @keystatic@latest`
2. `pnpm update`
3. `pnpm dev`
4. Open http://127.0.0.1:4321/keystatic

Result:
![chrome_01dqxJ7i40](https://github.com/Thinkmill/keystatic/assets/138311/fb5a52d5-55e0-46bf-a917-f0679b288602)

It works fine when I downgrade to `@keystatic/astro@2.0.3`

**Comment by vincentdorian** [comment]
Same here. The folder /internals does not seem to exist in version 3.0
