### ISSUE TITLE
Not deploying Keystatic to production, is it possible?

### ISSUE THREAD

**Issue by Angelfire** [Thinkmill/keystatic#915]
Basically I need Keystatic only for the development environment, to use it as an editor for my markdown files in Astro, but I don't want to have it in production, I don't find it necessary (plus it would add an extra layer of complexity and security), fix a bug in production It is as easy as editing a .md or .mdx file on GitHub, is it possible to configure Keystatic only for development?

**Comment by emmatown** [comment]
https://keystatic.com/docs/recipes/astro-disable-admin-ui-in-production explains how you can do this
