### ISSUE TITLE
[GraphQL] Resource not accessible by integration

### ISSUE THREAD

**Issue by ChristianSantanaLlanes** [Thinkmill/keystatic#939]
I'm using the Astro starter and when I integrate it with GitHub and deploy it on Vercel, I get this error when trying to edit or create any element in the dashboard.

Error: [GraphQL] Resource not accessible by integration

**Comment by linxOD** [comment]
This errors can be solved by manually installing the Github App via -> Settings -> Developer settings -> Github Apps. Click on "Edit" and open the "Public Url" of you app. Click "Install" and follow the instructions. Make sure you open "settings" of you personal account or Github Organization.

The BUG related to Keystatic is that durung Github App Creation (as documented) the redirect URL callback to install the App does not work.
