### ISSUE TITLE
Keystatic does not respect the "owner" value in the config file for GitHub Mode

### ISSUE THREAD

**Issue by solelychloe** [Thinkmill/keystatic#944]
This is a critical issue. And as the title says, basically.

I've noticed on the #astro channel in the Keystatic Discord server that anyone can go to the `/keystatic` path and authorize via GitHub, and Keystatic will happily let them in.

This happens both when `repo` has the `owner` and `repo` properties or when `repo` is a template literal (`GITHUB_OWNER/GITHUB_REPO_NAME`).

**Comment by emmatown** [comment]
This is intentional behaviour, the `owner` field is just to refer to the repo, not the only person who can access it. The GitHub app allows anyone to login and they will have access to it depending on if the repo is public and their permissions on the repo.
