### ISSUE TITLE
Production github auth only authenticates once

### ISSUE THREAD

**Issue by felipemullen** [Thinkmill/keystatic#978]
I am having trouble running in Github mode in production. I have found a few similar issues listed in the repo (#298), but so far nothing has solved the problem for me.

- Github app was created during local development
- I have set the environment variables necessary and deployed on `railway.app` (similar to vercel):

```.env
KEYSTATIC_GITHUB_CLIENT_ID=Iv1.2addc090b1298ab5
KEYSTATIC_GITHUB_CLIENT_SECRET=#####
KEYSTATIC_SECRET=#####
NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=ind3x-web-keystatic
```

When the app is first installed on the github user and redirected to the keystatic page, auth works. The token is stored, everything is great.

If I log out from keystatic, or github, or I try to use another device, I always see this error:

```text
An error occurred when trying to authenticate with GitHub:
The redirect_uri MUST match the registered callback URL for this application.

If you were trying to sign in locally and recently upgraded Keystatic from @keystatic/core@0.0.69 or below, you need to add `http://127.0.0.1/api/keystatic/github/oauth/callback` as a callback URL in your GitHub app.
```

To be clear, the 127.0.0.1 urls are no longer a part of the app configuration, I have updated the GH App with a single callback url `https://ind3x.games/api/keystatic/github/oauth/callback`.

I have tried to uninstall, install again, nothing seems to fix it permanently. It always works once, during the install redirect, never again.

**Comment by pkellner** [comment]
I had this same error for a while and I was convinced everything was broken. Turns out that I was confused on what URL I was actually browsing to, and the URL that is buried inside the github application. I've been using vercel and they actually create two URL's for a single project. For me, one was https://vercel.com/pkellner/artpark-astro-proto2/879VvXK9XgXzHYGkFU3edUYYcGnr and the other was https://artpark-astro-proto2.vercel.app/.  The app had the wrong one in it which is exactly what the error was saying (sort of).

I don't mean to clutter up the issue, but for me it turned out to be pretty simple once I really looked closely at both URL's. HTH's.

**Comment by felipemullen** [comment]
@pkellner thanks for the insight. Could a cloudflare proxy have an effect on what the redirect expects? Currently the app is running like this:

- app runs inside of container in railway at `http://localhost:4321` which is exposed via unique app `u9yqow7n.up.railway.app`
- cloudflare proxies `https://ind3x.games` to `u9yqow7n.up.railway.app` via CNAME record
- github app callback url is `https://ind3x.games/api/keystatic/github/oauth/callback`

Perhaps the github app be configured with a different url?

**Comment by felipemullen** [comment]
During app login I see the url generated by the github app:
```text
https://github.com/login?client_id=Iv1.2addc090b1298ab5&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3DIv1.2addc090b1298ab5%26redirect_uri%3Dhttps%253A%252F%252F127.0.0.1%253A3000%252Fapi%252Fkeystatic%252Fgithub%252Foauth%252Fcallback
```

A quick decode gives us

```javascript
decodeURIComponent('https%3A%2F%2F127.0.0.1%3A3000%2Fapi%2Fkeystatic%2Fgithub%2Foauth%2Fcallback');
// 'https://127.0.0.1:3000/api/keystatic/github/oauth/callback'
```

This is strange to me because the app is definitely configured with a single url as seen in the following image:

<img width="757" alt="image" src="https://github.com/Thinkmill/keystatic/assets/3488482/62ec64bf-21e3-41ff-abd3-aaf605380f83">

**Comment by pkellner** [comment]
@felipemullen you have gone through the exact same thing I did when I said "huh?" that's different. I don't know much about cloudfare, but it sounds like you are on to the problem. Maybe if you add to the github app the one you are calling? that is, add the `u9yqow7n.up.railway.app` with the auth stuff to the github app?

**Comment by felipemullen** [comment]
well I managed to fix it. But it sure is hacky if you ask me, so if anyone has a better solution please update this thread.

**The problem**

- Next.js seems to always run using `localhost` as a hostname, and although I spent hours scouring the documentation and the internet, I could not find a way to change the hostname apart from the `--hostname` cli argument.
- However, I am hosting on [railway.app](https://railway.app) and specifying the hostname causes the server to fail to start.
- Keystatic uses the [url origin](https://github.com/Thinkmill/keystatic/blob/main/packages/keystatic/src/api/generic.ts#L377) when redirecting to github's oauth urls, but *I am stuck using localhost*

**My solution**

I wrapped the keystatic api handlers in `api/keystatic/[...params]/route.ts` to modify the request url so there is no confusion about the host:

```typescript
import { makeRouteHandler } from '@keystatic/next/route-handler';
import keystaticConfig from '../../../../../keystatic.config';

const { POST: ksPOST, GET: ksGET } = makeRouteHandler({
    config: keystaticConfig,
});

function rewriteHostname(request: Request) {
    const url = new URL(request.url);
    if (process.env.HOST_OVERRIDE) {
        url.hostname = process.env.HOST_OVERRIDE;
        url.protocol = 'https';
        url.port = '443';
    }

    return new Request(url.toString(), request);
}

export function GET(request: Request) {
    return ksGET(rewriteHostname(request));
}

export function POST(request: Request) {
    return ksPOST(rewriteHostname(request));
}
```

I kind of hate it, but it is working now.
