### ISSUE TITLE
404 on Github login on Cloudflare

### ISSUE THREAD

**Issue by NoelOConnell** [Thinkmill/keystatic#987]
The `/keystatic` page renders the "login with Github" button but clicking that gives a 404.

From the logs in Cloudflare
```
 "logs": [
    {
      "message": [
        "10:14:19 [WARN] [router] No API Route handler exists for the method \"GET\" for the route \"/api/keystatic/github/login\".\nFound handlers: \"ALL\", \"prerender\"\n"
      ],
      "level": "log",
      "timestamp": 1709806459296
    }
  ],
  ```
  
It seems that the handler is null  https://github.com/withastro/astro/blob/e88eeb033749bd6bce8c00e712e207690ae9bf79/packages/astro/src/runtime/server/endpoint.ts#L26

It's a empty site with just a single `index.astro` page.
This is what gets built and uploaded to Cloudflare.
![image](https://github.com/Thinkmill/keystatic/assets/966495/326087d5-1431-4ce8-b379-e08177cd2f0f)

Here's the dependency list
```
"dependencies": {
    "@astrojs/cloudflare": "^9.0.2",
    "@astrojs/markdoc": "^0.9.0",
    "@astrojs/react": "^3.0.10",    
    "@keystatic/astro": "^5.0.0",
    "@keystatic/core": "^0.5.0",
    "@tailwindcss/forms": "^0.3.3",
    "@tailwindcss/typography": "^0.4.1",
    "@types/react": "^18.2.55",
    "@types/react-dom": "^18.2.19",
    "astro": "^4.4.10"
    ....
    }
```

I also forked Emma's [Keystatic Cloudfare demo repo](https://github.com/emmatown/keystatic-astro-cloudflare-workers-test) and updated packages and it shows the same issue.

**Comment by emmatown** [comment]
I just upgraded https://github.com/emmatown/keystatic-astro-cloudflare-workers-test and it seems to be working fine?

**Comment by NoelOConnell** [comment]
Thanks for the reply, I updated my fork to match your recent changes and still have the same issue.

https://keystatic-astro-cloudflare-workers-test-env.pages.dev/
https://github.com/NoelOConnell/keystatic-astro-cloudflare-workers-test

It deploys fine and the site works but I can't get pass the "login with Github" button on the `/keystatic` page so I can't go through the Github setup flow as per the docs. 
https://keystatic.com/docs/github-mode#connecting-with-git-hub

Is there any specific Cloudflare options/configuration required? 
Is there a way to setup the Github app another way to see if that is the part causing the issue?

**Comment by jossmac** [comment]
@NoelOConnell can this issue be closed?

**Comment by emmatown** [comment]
The GitHub App setup flow asks for the deployed URL so it can also add that URL as a callback URL as well but if that's missing then naturally you have to go into the GitHub App settings to add it yourself so everything here seems to working fine

**Comment by m4rrc0** [comment]
For reference: I had the same issue and it was simply because I was missing the `KEYSTATIC_SECRET` env variable in Cloudflare.
