### ISSUE TITLE
Field validation failed: content: Unexpected error: TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by zanhk** [Thinkmill/keystatic#996]
Getting the error

"Field validation failed: content: Unexpected error: TypeError: Cannot read properties of undefined (reading 'map')"

![image](https://github.com/Thinkmill/keystatic/assets/17980844/f620b48b-8e4c-4695-b042-2f24b5c375c8)

When using fields.array inside a custom component:

```js
content: fields.markdoc({
	label: "Content",
	options: {
		heading: [2, 3, 4, 5, 6],
	},
	components: {
		ContactWithForm: block({
			label: "Form di contatto",
			icon: ContactIcon({ ariaHidden: true }),
			description: "Personalizza le informazioni relative alla form di contatto",
			schema: {
				title: fields.text({
					label: "Titolo",
					validation: {
						isRequired: true,
					},
				}),
				subtitle: fields.text({
					label: "Sottotitolo",
					validation: {
						isRequired: true,
					},
				}),
				email: fields.text({
					label: "Email",
					validation: {
						isRequired: true,
					},
				}),
				phone: fields.text({
					label: "Telefono",
					validation: {
						isRequired: true,
					},
				}),
				timetables: fields.array(fields.text({ label: "Time" }), { // <- Here causing the problem
					label: "Time",
					itemLabel: (props) => props.value,
				}),
			},
		}),
	},
}),
```

(example from https://keystatic.com/docs/fields/array#simple)

Is this something that is supported by keystatic?

Thanks

**Comment by emmatown** [comment]
I can't reproduce this error here, could you share the content that this fails with?

**Comment by zanhk** [comment]
I reproduced the problem and now that I know it's just a minor inconvenience:

To reproduce you have to add an `fields.array` to an existing element on the page, for reference here's what happen when you add  a new `fields.text` to the collection schema

[google_screen_recording_2024-03-12T17-55_03.468Z.webm](https://github.com/Thinkmill/keystatic/assets/17980844/cd0f2f16-6644-482c-90c0-ef9c3939d656)

and here what happen when you add a `fields.array` 

[google_screen_recording_2024-03-12T17-56_57.685Z.webm](https://github.com/Thinkmill/keystatic/assets/17980844/19faf248-ce43-4835-af6c-cdc666b470e8)
o an existing element on the page
